import React from "react";

const MessageUI = ({ text }) => {
	return <div className="w-[90%] max-w-[300px] h-fit bg-indigo flex justify-start items-center pl-3 py-3 my-5 rounded-xl">{text}</div>;
};

const Features = () => {
	return (
		<div className="w-full h-fit flex justify-center items-center flex-wrap lg:px-10 mb-10 gap-10">
			<div className="w-full md:w-1/2 max-w-[700px] md:min-w-[500px] h-fit flex flex-col justify-center items-start z-[2] px-2">
				<h1 className="text-blackMagic text-xl md:text-3xl font-semibold mb-5">AI Based Response & Title Generation</h1>
				<p className="text-blackMagic text-sm md:text-lg mb-3">
					To generate controlled response from ChatGPT AI,Prompt Designing method is used. Based on this method, ChatGPT will check user input and reply accordingly
				</p>
				<p className="text-blackMagic text-sm md:text-lg">Title is generated by ChatGPT itself and It is used to show what particular chat contains</p>
			</div>
			<div className="w-full lg:w-1/2 h-fit max-w-[500px] z-[2]">
				<div className="w-full max-w-[500px] bg-ghostWhite mx-auto aspect-[5/7] rounded-2xl shadow-xl flex justify-center items-center py-10">
					<div className="relative w-[80%] bg-blackMagic aspect-[5/7] px-1 pt-20">
						<h1 className="absolute top-2 left-2">Projectile Motion</h1>
						<div className="w-full h-fit flex justify-end items-center">
							<MessageUI text="What is projectile motion?" />
						</div>
						<div className="w-full h-fit flex justify-start items-center">
							<MessageUI text="Projectile motion is a form of motion where an object moves in a parabolic path under the influence of gravity." />
						</div>
						<div className="w-full h-fit flex justify-end items-center">
							<MessageUI text="How to learn programming?" />
						</div>
						<div className="w-full h-fit flex justify-start items-center">
							<MessageUI text="This is not physics related question. Please ask me something related to physics" />
						</div>
					</div>
				</div>
			</div>
		</div>
	);
};

export default Features;
